apiVersion: v1
kind: Namespace
metadata:
  name: monitoring
---
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: prometheus
  namespace: kube-system
spec:
  chart: stable/prometheus
  targetNamespace: monitoring
  valuesContent: |-
      grafana:
        enabled: false
      alertmanager:
        enabled: false
      server:
        ingress:
          enabled: true
          hosts:
          - prom.localtest.me
        securityContext:
          fsGroup: 65534
          runAsGroup: 0
          runAsNonRoot: false
          runAsUser: 0
---